apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-nginx
  labels:
    app: laravel-app
    name: laravel-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      name: laravel-nginx
  template:
    metadata:
      labels:
        app: laravel-app
        name: laravel-nginx
    spec:
      containers:
        - name: laravel-nginx
          image: adisu33/laravel-nginx-test:latest
          ports:
            - containerPort: 80
