apiVersion: v1
kind: Service
metadata:
  labels:
    name: laravel-nginx
  name: laravel-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 80
  selector:
    name: laravel-nginx
  # type: NodePort
