apiVersion: v1
kind: Service
metadata:
  labels:
    name: laravel-nginx
  name: laravel-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: laravel-nginx
  # type: NodePort
